application: exquisiteclockapi
version: 1
runtime: python
api_version: 1

handlers:

- url: /js
  static_dir: js
  
- url: /css
  static_dir: css

- url: /imgs
  static_dir: imgs

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /feed_sample\.json
  static_files: feed_sample.json
  upload: feed_sample\.json

- url: /backend/.*
  script: updater.py
    
- url: /.*
  script: main.py


